import type { Country } from "../types/index.js";

export const SUPPORTED_COUNTRIES: Country[] = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas",
  "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize",
  "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
  "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
  "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China",
  "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the",
  "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark",
  "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt",
  "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
  "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany",
  "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau",
  "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia",
  "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "North Korea", "South Korea", "Kosovo",
  "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia",
  "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi",
  "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
  "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia",
  "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
  "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
  "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine",
  "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
  "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis",
  "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
  "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
  "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan",
  "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan",
  "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
  "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "UAE", "UK",
  "USA", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela",
  "Vietnam", "Yemen", "Zambia", "Zimbabwe", "British Virgin Islands",
  "Curaçao", "St. Maarten", "Turks & Caicos Islands", "Cayman Islands"
];

export function isValidCountry(country: string): country is Country {
  return SUPPORTED_COUNTRIES.includes(country as Country);
}

export function getCountryValidationMessage(invalidCountry: string): string {
  return `Invalid country name "${invalidCountry}". Must be one of the supported countries: ${SUPPORTED_COUNTRIES.slice(0, 10).join(", ")}... (and ${SUPPORTED_COUNTRIES.length - 10} more)`;
}

export const SUPPORTED_INDUSTRIES = [
  "Accounting",
  "Agriculture & Farming",
  "Airlines & Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Architecture & Planning",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking & Mortgage",
  "Biotechnology",
  "Broadcast Media",
  "Building and construction",
  "Business Supplies & Equipment",
  "Capital Markets/Hedge Fund/Private Equity",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software/Engineering",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense & Space",
  "Design",
  "E-commerce & Online Stores",
  "E-Learning",
  "Education",
  "Electrical & Electronic Manufacturing",
  "Energy & Utilities",
  "Entertainment & Movie Production",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Fashion & Apparel",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food & Beverages",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling & Casinos",
  "Gaming",
  "Glass, Ceramics & Concrete",
  "Government & Public Sector",
  "Government Administration",
  "Government Relations",
  "Graphic & Web Design",
  "Health & Fitness",
  "Healthcare & Pharmaceuticals",
  "Higher Education/Acadamia",
  "Hospital & Health Care",
  "Hospitality & Tourism",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology (IT) Services",
  "Insurance",
  "International Affairs",
  "International Trade & Development",
  "Investment Management, Hedge Fund & Private Equity",
  "Judiciary",
  "Law Enforcement",
  "Law Practice & Law Firms",
  "Legal Services",
  "Legislative Office",
  "Leisure & Travel",
  "Library",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Manufacturing & Industrial Products",
  "Maritime",
  "Market Research",
  "Marketing, Advertising & Sales",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Equipment Manufacturing",
  "Medical Practice",
  "Mental Health Care",
  "Military Industry",
  "Mining/Metals",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Music",
  "Nanotechnology",
  "Network & Telecommunications",
  "Newspapers & Journalism",
  "Non-profit & Social Organizations",
  "Oil & Gas",
  "Online Publishing",
  "Other Industry",
  "Outsourcing & Offshoring",
  "Package & Freight Delivery",
  "Packaging & Containers",
  "Paper & Forest Products",
  "Performing Arts",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Printing",
  "Professional Services",
  "Professional Training",
  "Program Development",
  "Public Relations/PR",
  "Public Safety",
  "Publishing Industry",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreational Facilities & Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research Industry",
  "Restaurants",
  "Retail Industry",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Social Media & Online Social Networking",
  "Software",
  "Sporting Goods",
  "Sports",
  "Staffing/Recruiting",
  "Supermarkets",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation & Localization",
  "Transportation & Logistics",
  "Venture Capital",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine & Spirits",
  "Wireless",
  "Writing & Editing",
  "Demolition Services"
] as const;

export function isValidIndustry(industry: string): boolean {
  return SUPPORTED_INDUSTRIES.includes(industry as any);
}

export function getIndustryValidationMessage(invalidIndustry: string): string {
  return `Invalid industry "${invalidIndustry}". Must be one of the supported industries: ${SUPPORTED_INDUSTRIES.slice(0, 10).join(", ")}... (and ${SUPPORTED_INDUSTRIES.length - 10} more)`;
} 